server {
    listen 80; # Assicurati che coincida con il mapping del compose
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Fondamentale per React Router
    }

    # Proxy per il backend (se non vuoi gestire i CORS in Java)
    # location /api/ {
    #     proxy_pass http://spring_backend:7000/;
    # }
}